<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>ZeissAssessment</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controllers\" />
      <Folder Include="Middleware\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ZeissAssessment.Application\ZeissAssessment.Application.csproj" />
      <ProjectReference Include="..\ZeissAssessment.Domain\ZeissAssessment.Domain.csproj" />
      <ProjectReference Include="..\ZeissAssessment.Infrastructure\ZeissAssessment.Infrastructure.csproj" />
    </ItemGroup>

</Project>
